### ISSUE TITLE
Inverting/Non-inverting inputs issue

### ISSUE THREAD

**Issue by tzhf** [benjiao/BufferedMixer#1]
Hi,
I noticed an issue in your layout, the first op amp block (1, 2, 3) is ok but all the others are inverted, Inverting and non-inverting inputs must be swapped, sadly i built it without checking, thanks anyway :p

**Comment by benjiao** [comment]
Hi @Tzhf, sorry about that. It might be too late, but i updated the drawings. Thank you very much for reporting!

**Comment by tzhf** [comment]
No problem, wasn't too hard to fix, thanks again for the design :)

**Comment by benjiao** [comment]
You're very welcome! Glad you like it

**Comment by tzhf** [comment]
the svg hasn't been updated i think, i cleared my cache but it's still the old one, just in case someone else makes the same mistake I made :p

**Comment by benjiao** [comment]
Oops. Should be good now. :slightly_smiling_face:
